# Generated by Django 3.1.6 on 2021-02-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_todo_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='TITLES',
            field=models.CharField(choices=[('P', 'Projects'), ('H', 'Household'), ('S', 'Shopping'), ('F', 'Finances'), ('W', 'Work'), ('T', 'Trips'), ('M', 'Misc')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
