# Generated by Django 3.1.6 on 2021-02-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210213_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='TITLES',
            new_name='title',
        ),
    ]
