# Generated by Django 3.1.6 on 2021-02-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210217_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='importance',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Moderate'), ('H', 'High')], default='L', max_length=1),
        ),
        migrations.DeleteModel(
            name='Importance',
        ),
    ]
